// Traducciones al español de los cues de técnica, por catalogId. Curado (IA), SEPARADO del
// archivo auto-generado (`exerciseMedia.data.ts`): re-ejecutar la ingesta NO debe pisarlo.
// Traducción fiel: NO agregar indicaciones que el original no tenga.
export const EXERCISE_CUES_ES: Record<string, string[]> = {
  alternating_dumbbell_lunge: [
    "Agarrá una mancuerna en cada mano.",
    "Pará con los pies separados unos 20 cm, las puntas hacia adelante.",
    "Dá un paso al frente (60-90 cm) manteniendo los abdominales metidos y el tronco derecho.",
    "Bajá despacio una rodilla como si te arrodillaras, manteniendo la otra rodilla flexionada a 90 grados; no dejes que la rodilla toque el piso.",
    "Bajá el cuerpo hasta que la rodilla de atrás quede justo por encima del piso y aguantá un momento antes de volver a la posición inicial.",
    "Repetí del lado opuesto.",
  ],
  arnold_press: [
    "Sentate en un banco plano, los pies apuntando hacia adelante y los abdominales metidos.",
    "Agarrá una mancuerna en cada mano con la palma mirando hacia el cuerpo.",
    "Flexioná los codos a 90 grados y llevá los dos brazos al punto de partida, a la altura de los hombros.",
    "Con un movimiento firme y controlado, subí los brazos estirando los codos mientras rotás los antebrazos hasta que las palmas queden mirando hacia afuera.",
    "Acercá las mancuernas entre sí, pero sin estirar los codos por completo.",
    "Con un movimiento controlado, bajá las mancuernas a la posición inicial en los hombros.",
  ],
  barbell_back_squat: [
    "Este es un ejercicio para fortalecer las piernas, sobre todo los cuádriceps.",
    "Sacá la barra del rack y apoyala sobre los hombros.",
    "Poné los pies un poco más abiertos que el ancho de hombros, con las rodillas y las puntas apuntando levemente hacia afuera.",
    "Con los abdominales metidos, bajá despacio flexionando rodillas y caderas, como si te sentaras (sentadilla).",
    "Bajá todo lo que puedas controlar sin que el cuerpo se vaya hacia las puntas de los pies (eso te hace perder el equilibrio).",
    "Hacé una pausa abajo y volvé despacio a la posición inicial.",
  ],
  barbell_bench_press: [
    "Acostate en un banco plano con los pies apoyados en el piso y la espalda pegada al banco.",
    "Agarrá la barra un poco más ancho que el ancho de hombros.",
    "Llevá la barra por encima del cuerpo hasta el medio del pecho: esa es la posición inicial.",
    "Bajá la barra hasta que roce el pecho.",
    "Subí la barra hasta estirar los brazos por completo, con los codos bloqueados.",
    "Volvé a la posición inicial.",
  ],
  barbell_biceps_curl: [
    "Este es un ejercicio básico para los bíceps (brazos).",
    "Pará con los pies al ancho de hombros, las rodillas apenas flexionadas y los abdominales metidos.",
    "Agarrá una barra con las palmas hacia arriba, aproximadamente al ancho de hombros.",
    "Bajá los brazos por completo hasta arriba de los muslos y, flexionando solo los codos, subí la barra hasta la parte alta del pecho.",
    "Hacé una pausa y volvé a la posición inicial.",
    "Nota: no balancees las caderas ni la espalda durante este ejercicio.",
  ],
  barbell_deadlift: [
    "Pará con los pies al ancho de hombros, de modo que queden debajo de la barra.",
    "Manteniendo la espalda recta, flexioná desde la cintura y permití algo de flexión en las rodillas.",
    "Agarrá la barra en pronación, con las manos separadas unos 40 cm.",
    "Enderezá la espalda mientras sostenés la barra con los brazos estirados.",
    "Volvé a inclinarte bajando la barra hasta justo por encima del piso.",
  ],
  barbell_front_squat: [
    "La sentadilla frontal trabaja los mismos músculos que la sentadilla trasera sin apoyar el peso de la barra sobre los hombros. Puede ser un buen reemplazo para quien tenga lesiones de espalda o cuello.",
    "Apoyá la barra en la parte alta del pecho, sobre los deltoides anteriores, sosteniéndola con los brazos cruzados de forma firme.",
    "Mantené la cabeza y la espalda derechas, los abdominales metidos y las puntas de los pies apenas hacia afuera.",
    "Bajá despacio en «sentadilla» hasta que los muslos queden paralelos al piso.",
    "Volvé despacio a la posición inicial.",
    "Nota: practicá la sentadilla sin peso para familiarizarte con el movimiento.",
  ],
  barbell_hack_squat: [
    "Esta es otra variante de la sentadilla básica, enfocada principalmente en los cuádriceps o músculos del muslo.",
    "Poné la barra en el piso justo detrás de las piernas y pará con los pies al ancho de hombros, con las puntas hacia adelante.",
    "Con los pies bien apoyados en el piso, agachate y agarrá la barra por detrás en pronación.",
    "Levantá la barra extendiendo caderas y rodillas, cuidando de no bloquear las rodillas.",
    "Bajá (sentadilla) hasta que los muslos queden paralelos al piso.",
    "Subí despacio a la posición inicial.",
  ],
  barbell_lunge: [
    "Empezá apoyando una barra sobre la parte alta de la espalda, con un agarre un poco más ancho que los hombros.",
    "Pará con los pies separados unos 20 cm, las puntas hacia adelante.",
    "Dá un paso al frente (60-90 cm) manteniendo los abdominales metidos y el tronco derecho.",
    "Bajá despacio una rodilla como si te arrodillaras, manteniendo la otra rodilla flexionada a 90 grados; no dejes que la rodilla toque el piso.",
    "Bajá el cuerpo hasta que la rodilla de atrás quede justo por encima del piso y aguantá un momento antes de volver a la posición inicial.",
    "Repetí del otro lado.",
  ],
  barbell_rollout: [
    "Poné una barra en el piso, a la altura de los pies.",
    "Flexionando desde la cintura, agarrá la barra en pronación al ancho de hombros.",
    "Con un movimiento lento y controlado, rodá la barra hacia adelante hasta que la espalda quede recta.",
    "Mantené los brazos estirados durante todo el ejercicio.",
    "Rodá de vuelta subiendo las caderas y la cola mientras volvés a la posición inicial.",
    "Nota: practicá subir las caderas y la cola lo más alto que puedas en este ejercicio.",
  ],
  barbell_shoulder_press: [
    "Sentado en un banco con soporte para barra, agarrá la barra con un agarre 8 a 10 cm más ancho que los hombros.",
    "Sacá la barra del soporte y bajala hasta la altura de los hombros.",
    "Manteniendo una buena postura, estirá los brazos y subí la barra por encima de la cabeza.",
    "Hacé una pausa y, con un movimiento controlado, bajá la barra a la posición inicial.",
  ],
  barbell_shrug: [
    "Pará en el piso con los abdominales metidos y la espalda recta.",
    "Agarrá una barra con un agarre un poco más ancho que los hombros, con los brazos estirados.",
    "Bajá los hombros todo lo que puedas para empezar.",
    "Subí los hombros lo más alto posible.",
    "Hacé una pausa arriba y volvé a la posición inicial con un movimiento controlado.",
    "Repetí.",
  ],
  barbell_step_up: [
    "Poné un banco, cajón o escalón delante tuyo.",
    "Agarrá una barra con agarre ancho y apoyala sobre los hombros.",
    "Con la pierna izquierda, subí al banco y después subí con la pierna derecha.",
    "Bajá con la pierna izquierda y después con la derecha.",
    "Repetí empezando con la pierna derecha.",
    "Nota: usá menos peso hasta que te acostumbres al movimiento de este ejercicio.",
  ],
  barbell_upright_row: [
    "Pará con los pies al ancho de hombros, los abdominales metidos y la espalda recta.",
    "Poné la barra en el rack en la posición en la que tus brazos quedan estirados adelante con los codos apenas flexionados.",
    "Poné las manos al ancho de hombros y subí la barra hacia el mentón con un movimiento controlado.",
    "Hacé una pausa arriba y juntá las escápulas.",
    "Bajá la barra a la posición inicial.",
    "Repetí",
  ],
  behind_the_back_smith_machine_shrug: [
    "Poné la barra a la altura de la cintura.",
    "Pará con los pies al ancho de hombros y los abdominales metidos.",
    "Agarrá la barra en pronación con los brazos estirados.",
    "Al levantar la barra, dejá que el peso te tire los hombros hacia abajo; después encogé los hombros hacia arriba y hacia atrás.",
    "Aguantá un momento y volvé a la posición inicial.",
  ],
  bench_dip: [
    "Este ejercicio es uno de los más básicos y sigue siendo de los mejores para construir los tríceps (músculos de la parte de atrás del brazo).",
    "Poné dos bancos paralelos, separados 1 a 1,2 metros.",
    "Sentate en uno y apoyá los pies en el borde del otro, de modo que las piernas queden suspendidas entre los dos bancos.",
    "Cruzá los pies para tener apoyo.",
    "Sostenete del banco con las manos y bajá despacio el cuerpo hacia el piso flexionando los codos.",
    "Hacé una pausa y volvé a la posición inicial.",
    "Nota: no bajes más allá de los 90 grados, porque puede afectarte los hombros.",
  ],
  bent_over_lateral_raise: [
    "Agarrá la manija de la polea baja con la mano derecha.",
    "Inclinate hacia adelante desde la cintura; el tronco tiene que quedar casi paralelo al piso. Flexioná un poco las rodillas y apoyá la mano izquierda sobre el muslo izquierdo. Dejá el brazo derecho colgando desde el hombro, adelante tuyo, con el codo apenas flexionado. Esa es la posición inicial.",
    "Subí el brazo derecho manteniendo el codo apenas flexionado.",
    "Seguí moviendo el brazo hasta que quede paralelo al piso, alineado con la oreja derecha.",
    "Bajá despacio el peso a la posición inicial.",
    "Hacé el ejercicio con el brazo izquierdo y repetí.",
  ],
  bicycle_crunch: [
    "Este ejercicio trabaja los abdominales llevando los brazos al encuentro de las piernas. El movimiento es parecido al de andar en bicicleta.",
    "Acostate boca arriba sobre una colchoneta.",
    "Poné las manos a los costados de la cabeza (sobre las orejas).",
    "Subí las piernas flexionando las rodillas y manteniendo las pantorrillas paralelas al piso.",
    "Llevá el codo del brazo izquierdo al encuentro de la rodilla derecha, como si pedalearas.",
    "Repetí con el codo derecho y la rodilla izquierda.",
    "Seguí alternando lados.",
    "Nota: movés los brazos cruzando el pecho, apretando los abdominales durante el movimiento.",
  ],
  body_weight_dip: [
    "Agarrate de un par de barras paralelas y subí hasta la posición inicial.",
    "Manteniendo los codos cerca del cuerpo, bajá hasta que los tríceps queden paralelos al piso.",
    "Subí despacio a la posición inicial.",
    "Nota: mantené los abdominales metidos y el cuerpo derecho durante este ejercicio.",
  ],
  cable_biceps_curl: [
    "Enganchá una barra corta a la polea baja de la torre de peso.",
    "Pará con los pies al ancho de hombros, las rodillas apenas flexionadas y los abdominales metidos.",
    "Agarrá la barra con las palmas hacia arriba y las manos bastante juntas.",
    "Bajá los brazos por completo hasta arriba de los muslos y, flexionando solo los codos, subí la barra hasta la parte alta del pecho.",
    "Hacé una pausa y volvé a la posición inicial.",
    "Nota: no balancees las caderas ni la espalda durante este ejercicio.",
  ],
  cable_crossover: [
    "Poné las poleas a la altura de los hombros.",
    "Agarrá una polea con cada mano y pará unos 30 cm delante de las torres de peso, con un pie apenas adelante del otro.",
    "Con los codos apenas flexionados, juntá las manos delante del pecho siguiendo un ángulo hacia abajo.",
    "Cuando las manos se junten en el medio del pecho, aguantá un momento.",
    "Con un movimiento lento y controlado, volvé a la posición inicial.",
  ],
  cable_front_raise: [
    "Poné la polea en la posición justo por encima del piso.",
    "Pará con los pies al ancho de hombros, los abdominales metidos y las rodillas apenas flexionadas.",
    "Empezando a la altura de la cintura, tomá la polea con la mano izquierda, la palma mirando al piso (agarre en pronación), y subí el brazo estirado hacia el hombro izquierdo.",
    "A la altura del hombro, hacé una pausa.",
    "Con un movimiento controlado, resistí el peso y bajá despacio el brazo a la posición inicial en la cintura.",
    "Repetí el ejercicio con el brazo derecho.",
  ],
  cable_hammer_curl: [
    "Usar la soga en la polea permite aislar los bíceps en esta versión del curl martillo. Es un buen ejercicio para principiantes.",
    "Enganchá una soga a la polea baja de la torre de peso. Pará con los pies al ancho de hombros, las rodillas apenas flexionadas y los abdominales metidos. Agarrá la soga con un agarre cerrado en supinación (palmas hacia arriba). Bajá los brazos por completo hasta arriba de los muslos y, flexionando solo los codos, subí la soga hasta la parte alta del pecho. Hacé una pausa y volvé a la posición inicial.",
    "Nota: mantené los codos al costado del cuerpo durante todo el ejercicio. No balancees las caderas ni la espalda.",
  ],
  cable_internal_rotation: [
    "Sentate en el piso con el cuerpo cerca de la polea baja.",
    "Agarrá la polea con el brazo izquierdo y poné el codo flexionado a 90 grados.",
    "Traé el cable hacia el cuerpo rotando el hombro hacia adentro hasta que el antebrazo cruce los abdominales.",
    "Volvé a la posición inicial.",
    "Repetí con el brazo derecho.",
  ],
  cable_lying_triceps_extension: [
    "Este ejercicio usa poleas para aislar y trabajar los tríceps (músculos de la parte de atrás del brazo).",
    "Poné un banco plano con la punta hacia la torre de peso.",
    "Enganchá una barra recta corta a la polea y bajá la polea al fondo de la torre.",
    "Acostate boca arriba en el banco y agarrá la barra en pronación con agarre cerrado.",
    "Empezando con los brazos estirados, bajá la barra hacia la torre flexionando los codos.",
    "Estirá despacio los brazos hacia arriba y volvé a la posición inicial.",
    "Nota: mantené los codos a la misma altura durante todo el ejercicio.",
  ],
  chin_up: [
    "Agarrá la barra en supinación.",
    "Dejá el cuerpo colgando de la barra con los brazos estirados.",
    "Traccioná despacio hasta que el mentón quede por encima de la barra.",
    "Con un movimiento controlado, bajá a la posición inicial.",
  ],
  close_grip_barbell_bench_press: [
    "Acostate en un banco plano con los pies apoyados en el piso y la espalda pegada al banco.",
    "Agarrá la barra con agarre cerrado (unos 35 cm entre las manos).",
    "Llevá la barra por encima del cuerpo hasta el medio del pecho: esa es la posición inicial.",
    "Bajá la barra hasta que roce el pecho.",
    "Subí la barra hasta estirar los brazos por completo, con los codos bloqueados.",
    "Volvé a la posición inicial.",
  ],
  close_grip_ez_bar_biceps_curl: [
    "Pará con los pies al ancho de hombros, las rodillas apenas flexionadas y los abdominales metidos.",
    "Agarrá una barra Z en supinación con agarre cerrado (unos 10 cm), en la parte más interna de la barra.",
    "Estirá los brazos por completo contra los muslos.",
    "Manteniendo los codos firmes, subí la barra hacia el pecho.",
    "Hacé una pausa y volvé a la posición inicial.",
    "Nota: apoyate contra una pared o un poste si te cuesta no balancearte.",
  ],
  close_grip_lat_pulldown: [
    "Enganchá un triángulo (barra en V) a la polea alta de la torre.",
    "Sentado derecho y con los abdominales metidos, agarrá el triángulo en pronación, con las palmas enfrentadas.",
    "Traccioná el agarre hacia abajo, derecho hasta la parte alta del pecho.",
    "Hacé una pausa después de tocar el pecho y llevá despacio el agarre a la posición inicial.",
    "Repetí.",
  ],
  cross_body_dumbbell_hammer_curl: [
    "Parado, agarrá una mancuerna en cada brazo con las palmas enfrentadas.",
    "Manteniendo las palmas enfrentadas (sin girar los brazos), subí la mancuerna hacia el hombro opuesto.",
    "Llevá la punta de la mancuerna hasta tocar el hombro.",
    "Despacio y de manera controlada, bajá la mancuerna a la posición inicial.",
  ],
  crunch: [
    "Este es el ejercicio abdominal más común y posiblemente el que peor se hace. Así se hace bien.",
    "Acostate boca arriba con los pies arriba de un banco y las rodillas flexionadas a 90 grados.",
    "Poné las manos cruzadas sobre el pecho o a los costados de la cabeza (sobre las orejas).",
    "Levantá la cabeza, los hombros y el pecho del piso hacia las rodillas, apretando los abdominales.",
    "Aguantá la posición un momento y bajá a la posición inicial.",
    "Nota: mantené las caderas firmes y la zona lumbar contra el piso durante este ejercicio.",
  ],
  decline_dumbbell_bench_press: [
    "Agarrá las mancuernas con las manos y acostate en un banco declinado, con la cabeza más abajo que los pies.",
    "Subí las mancuernas por encima del pecho, con los codos cerca del cuerpo: esa es la posición inicial.",
    "Despacio y con control, bajá las mancuernas a los costados de la parte baja del pecho.",
    "Subí las mancuernas de vuelta a la posición inicial.",
  ],
  decline_dumbbell_flye: [
    "Acostate en un banco declinado con la cabeza más abajo que el cuerpo y los pies bien apoyados en el piso.",
    "Con las mancuernas juntas por encima de los hombros y los brazos estirados hacia arriba: esa es la posición inicial.",
    "Manteniendo los brazos estirados con una leve flexión en los codos, bajá las mancuernas hacia el piso en arco, hasta justo por encima de los hombros.",
    "Volvé a la posición inicial de manera lenta y controlada.",
    "Repetí.",
  ],
  diamond_push_up: [
    "Esta versión de la flexión aísla los tríceps (parte de atrás del brazo).",
    "Arrodillate en el piso o en una colchoneta, poné las manos con los pulgares juntos y subí sobre las puntas de los pies.",
    "Meté los abdominales y mantené la espalda y el cuello alineados.",
    "Bajá despacio el cuerpo hacia el piso flexionando los brazos, hasta quedar casi tocando el piso.",
    "De manera controlada, subí el cuerpo de vuelta a la posición inicial.",
  ],
  donkey_calf_raise: [
    "Este es un ejercicio de gimnasio a la vieja usanza que necesita la ayuda de otra persona. Es un ejercicio avanzado y no se recomienda para principiantes.",
    "Flexioná desde la cintura y apoyá los brazos contra un rack o un banco a la altura de la cintura.",
    "Pedile a un compañero que se siente sobre tu zona lumbar.",
    "Subí sobre las puntas de los pies inclinándote apenas hacia adelante.",
    "Hacé una pausa arriba y bajá los talones al piso.",
    "Nota: pedile a un entrenador o instructor que te muestre cómo hacer este ejercicio de forma segura.",
  ],
  dumbbell_bench_press: [
    "Este es un ejercicio para fortalecer el pecho, los tríceps y los hombros.",
    "Agarrá las mancuernas en cada mano y acostate en un banco plano con los pies bien apoyados en el piso.",
    "Estirá los brazos por encima del pecho con las palmas hacia adelante.",
    "Empujá las mancuernas por encima del pecho hasta estirar los brazos por completo: esa es la posición inicial.",
    "Flexioná los codos a 90 grados de modo que los brazos queden paralelos al piso.",
    "Bajá despacio las mancuernas todo lo que te resulte cómodo, a lo largo del pecho.",
    "Con un movimiento controlado, volvé a la posición inicial.",
    "Repetí.",
  ],
  dumbbell_biceps_curl: [
    "Pará con los pies al ancho de hombros, las rodillas apenas flexionadas y los abdominales metidos.",
    "Agarrá una mancuerna en cada mano con las palmas hacia arriba.",
    "Estirá los brazos de modo que queden a los costados del cuerpo.",
    "Manteniendo los codos fijos, subí los brazos hacia el pecho hasta que los antebrazos toquen los bíceps.",
    "De manera lenta y controlada, bajá los brazos a la posición inicial.",
    "Nota: no balancees el cuerpo mientras hacés este ejercicio.",
  ],
  dumbbell_deadlift: [
    "Agarrá 2 mancuernas y pará con los pies al ancho de hombros.",
    "Manteniendo la espalda recta, flexioná desde la cintura y permití algo de flexión en las rodillas.",
    "Agarrá las mancuernas en pronación, una en cada mano.",
    "Enderezá la espalda mientras sostenés las mancuernas con los brazos estirados.",
    "Volvé a inclinarte bajando las mancuernas hasta justo por encima del piso.",
    "Volvé a la posición inicial.",
    "Repetí.",
  ],
  dumbbell_flye: [
    "Acostate en un banco plano con una mancuerna en cada mano y los pies bien apoyados en el piso.",
    "Subí las mancuernas por encima del pecho estirando los brazos por completo con una leve flexión en los codos: esa es la posición inicial.",
    "Manteniendo una leve flexión en los codos, bajá las mancuernas hacia el piso describiendo un arco.",
    "Volvé despacio con las mancuernas por encima del pecho a la posición inicial, con un movimiento controlado.",
    "Repetí.",
  ],
  dumbbell_front_raise: [
    "Pará con una mancuerna en cada mano en pronación, los pies al ancho de hombros y los abdominales metidos.",
    "Manteniendo cada brazo estirado, subí el brazo izquierdo hasta justo por encima de la altura del hombro.",
    "Hacé una pausa y, con un movimiento controlado, bajá el peso a la posición inicial y repetí con el brazo derecho.",
    "",
  ],
  dumbbell_hammer_curl: [
    "Este ejercicio usa un movimiento de martillo (arriba y abajo) para aislar los bíceps.",
    "Pará con los pies al ancho de hombros, las rodillas apenas flexionadas y los abdominales metidos.",
    "Agarrá una mancuerna en cada mano con las palmas enfrentadas.",
    "Estirá los brazos de modo que queden a los costados del cuerpo.",
    "Manteniendo los codos fijos, subí los brazos en arco hacia los hombros.",
    "Bajá los brazos con un movimiento firme y controlado, y repetí.",
    "Nota: no gires las muñecas durante este ejercicio.",
  ],
  dumbbell_kickback: [
    "Parado al costado de un banco plano, flexioná la rodilla izquierda y apoyala sobre el banco.",
    "Apoyá la mano izquierda en el banco para sostenerte, manteniendo la espalda a 45 grados.",
    "Sostené una mancuerna con la mano derecha y apoyá el pie derecho en el piso.",
    "Flexioná el brazo derecho y subilo hasta el hombro; después, con un movimiento controlado, llevalo hacia atrás estirando el brazo por completo.",
    "Cambiá de brazo y repetí.",
    "Nota: mantené el codo cerca del cuerpo durante este ejercicio.",
  ],
  dumbbell_lateral_raise: [
    "Agarrá una mancuerna en cada mano, con las palmas mirando hacia el cuerpo y las mancuernas a los costados.",
    "Parado con los pies al ancho de hombros, meté los abdominales y flexioná apenas las rodillas.",
    "Manteniendo el torso quieto, subí los brazos hacia los costados, estirados con una leve flexión en los codos.",
    "Subí los brazos hasta que queden alineados con los hombros; las palmas deberían mirar al piso.",
    "Aguantá la posición un momento y, con un movimiento controlado, bajá los brazos a la posición inicial.",
    "Repetí",
  ],
  dumbbell_lunge: [
    "Agarrá una mancuerna en cada mano.",
    "Pará con los pies separados unos 20 cm, las puntas hacia adelante.",
    "Dá un paso al frente (60-90 cm) manteniendo los abdominales metidos y el tronco derecho.",
    "Bajá despacio una rodilla como si te arrodillaras, manteniendo la otra rodilla flexionada a 90 grados; no dejes que la rodilla toque el piso.",
    "Bajá el cuerpo hasta que la rodilla de atrás quede justo por encima del piso y aguantá un momento antes de volver a la posición inicial.",
    "Repetí del lado opuesto.",
  ],
  dumbbell_lying_triceps_extension: [
    "Acostate en un banco plano con la cabeza en una punta y los pies bien apoyados en el piso.",
    "Agarrá una mancuerna con las dos manos, con las palmas hacia arriba.",
    "Subí la mancuerna por encima del cuerpo. Los brazos van a quedar apuntando al techo.",
    "Manteniendo los brazos y los codos quietos, bajá la mancuerna en arco por detrás de la cabeza.",
    "Subí despacio la mancuerna a la posición inicial.",
  ],
  dumbbell_shoulder_press: [
    "Sentado en un banco, con los abdominales metidos, agarrá una mancuerna en cada mano con las palmas hacia adelante.",
    "Empezá con los brazos a la altura de los hombros.",
    "Estirá los brazos y subí las mancuernas por encima de la cabeza.",
    "Arriba del movimiento, acercá los brazos entre sí.",
    "Hacé una pausa y, con un movimiento controlado, bajá las mancuernas a la posición inicial.",
    "Repetí",
  ],
  dumbbell_shrug: [
    "Pará con los pies al ancho de hombros y una leve flexión en las rodillas.",
    "Sostené una mancuerna en cada mano con los brazos a los costados.",
    "Bajá los hombros todo lo que puedas.",
    "Con los brazos estirados, subí los dos hombros hacia las orejas.",
    "Aguantá la posición de arriba un momento y bajá con un movimiento controlado.",
  ],
  dumbbell_squat: [
    "Este es un gran ejercicio general para el tren inferior que usa mancuernas en lugar de barra. A los principiantes esta versión puede resultarles más fácil.",
    "Agarrá una mancuerna en cada mano.",
    "Pará con los pies un poco más abiertos que el ancho de hombros, con las rodillas y las puntas apuntando levemente hacia afuera.",
    "Con los abdominales metidos, bajá despacio flexionando rodillas y caderas, como si te sentaras (sentadilla).",
    "Bajá todo lo que puedas controlar sin que el cuerpo se vaya hacia las puntas de los pies (eso te hace perder el equilibrio).",
    "Hacé una pausa abajo y volvé despacio a la posición inicial.",
    "Nota: practicar la sentadilla sin peso te va a permitir familiarizarte con el movimiento.",
  ],
  dumbbell_step_up: [
    "Poné un banco, cajón o escalón delante tuyo.",
    "Agarrá una mancuerna en cada mano.",
    "Con la pierna izquierda, subí al banco y después subí con la pierna derecha.",
    "Bajá con la pierna izquierda y después con la derecha.",
    "Repetí empezando con la pierna derecha.",
    "Nota: usá menos peso hasta que te acostumbres al movimiento de este ejercicio.",
  ],
  dumbbell_upright_row: [
    "Agarrá una mancuerna en cada mano en pronación (palmas hacia abajo) y sostenelas delante de los muslos.",
    "Pará con los pies al ancho de hombros, los abdominales metidos y la espalda recta.",
    "Empezando con las mancuernas en los muslos, subilas despacio hacia los hombros flexionando los codos.",
    "Hacé una pausa arriba y juntá las escápulas.",
    "Bajá las mancuernas a los muslos con un movimiento controlado.",
    "Repetí",
  ],
  ez_bar_overhead_triceps_extension: [
    "Pará con los pies al ancho de hombros, la espalda recta y los abdominales metidos.",
    "Sostené una barra o una barra Z con las manos separadas unos 15-20 cm y las palmas hacia arriba.",
    "Subí la barra por encima de la cabeza y bajala despacio en arco por detrás de la cabeza, hacia la espalda.",
    "Subí despacio la barra a la posición inicial.",
    "Nota: mantené los codos cerca de la cabeza durante el ejercicio",
  ],
  ez_bar_preacher_curl: [
    "",
    "Ajustá el asiento del banco para que los brazos queden a la altura de la parte de arriba del apoyo.",
    "Agarrá la barra con las palmas hacia arriba, al ancho de hombros.",
    "Levantando la barra, apoyá los brazos contra el banco y estiralos por completo.",
    "Manteniendo los brazos apoyados en el banco en todo momento, subí la barra hacia la cabeza.",
    "Hacé una pausa y bajá la barra a la posición inicial.",
    "Nota: hacé este ejercicio de manera lenta y controlada para mejores resultados.",
  ],
  ez_bar_pullover: [
    "Acostate en un banco plano con la cabeza apenas por fuera de la punta y los pies apoyados en el piso.",
    "Sostené una barra con agarre cerrado (unos 35 cm) y mantené los codos cerca durante todo el ejercicio.",
    "Empezando con los brazos estirados por completo sobre el pecho, bajá despacio la barra en arco por detrás de la cabeza, hacia el piso.",
    "Traccioná la barra de vuelta a la altura del pecho de manera lenta y controlada, y volvé a la posición inicial.",
    "Repetí.",
  ],
  flutter_kicks: [
    "Acostate boca abajo en un banco con las caderas en el borde, sosteniéndote del banco con las manos.",
    "Dejá que las piernas y las puntas de los pies cuelguen.",
    "Meté los abdominales y apretá los glúteos y los isquiotibiales.",
    "Pateá cada pierna hacia atrás y arriba manteniendo las caderas sobre el banco.",
    "Alterná las patadas de cada pierna.",
  ],
  front_raise: [
    "Pará con los pies al ancho de hombros, los abdominales metidos y las rodillas apenas flexionadas.",
    "Agarrá una mancuerna en cada mano, con la palma hacia abajo.",
    "Empezá con la mancuerna a la altura de la cintura.",
    "Subí el brazo izquierdo, manteniendo el codo apenas flexionado y el brazo estirado, hasta alinearlo con el hombro.",
    "Hacé una pausa y, con un movimiento controlado, bajá el brazo a la posición inicial en la cintura.",
    "Repetí con el brazo derecho.",
  ],
  incline_barbell_bench_press: [
    "Acostate en un banco inclinado a 45 grados, con los pies al ancho de hombros.",
    "Agarrá la barra un poco más ancho que el ancho de hombros.",
    "Llevá la barra por encima del cuerpo hasta el medio del pecho: esa es la posición inicial.",
    "Bajá la barra hasta que roce el pecho.",
    "Subí la barra derecho hasta estirar los brazos por completo, con los codos bloqueados.",
    "Volvé a la posición inicial.",
  ],
  incline_dumbbell_bench_press: [
    "Acostate en un banco inclinado a 45 grados.",
    "Empezá con las mancuernas a la altura de los hombros, los brazos abiertos y los codos apuntando al piso.",
    "Agarrá las mancuernas de modo que las palmas queden enfrentadas.",
    "Subí los brazos por encima del pecho acercando las mancuernas hasta que se junten sobre el pecho, como si aplaudieras.",
    "Volvé despacio con las mancuernas a la posición inicial.",
  ],
  incline_dumbbell_flye: [
    "Acostate en un banco inclinado a 45 grados con una mancuerna en cada mano y los pies bien apoyados en el piso.",
    "Subí las mancuernas por encima del pecho estirando los brazos por completo, con las palmas enfrentadas.",
    "Manteniendo una leve flexión en los codos, bajá las mancuernas hacia el piso describiendo un arco.",
    "Volvé despacio a la posición inicial.",
  ],
  incline_smith_machine_bench_press: [
    "Poné un banco inclinado a 45 grados en el medio de la máquina Smith.",
    "Alineá el banco de modo que la barra quede a la altura de la parte alta del pecho.",
    "Agarrá la barra al ancho de hombros.",
    "Destrabá la barra y bajá despacio el peso hasta el pecho; no rebotes la barra en el pecho.",
    "Con movimientos lentos y controlados, subí la barra a la posición inicial.",
  ],
  leg_lift: [
    "Usando un poste o un banco alto para el equilibrio, pará derecho con los abdominales metidos.",
    "Levantá una pierna del piso y llevala hacia atrás mientras te sostenés sobre la otra.",
    "Bajá despacio la pierna y volvé a subirla contrayendo los glúteos.",
    "Repetí con la otra pierna.",
  ],
  leg_press: [
    "Junto con la sentadilla, este ejercicio es clave para construir y fortalecer las piernas.",
    "Ajustá el asiento de la máquina para que los pies lleguen cómodos a la plataforma con una leve flexión en las rodillas.",
    "Para empezar, empujá los pies hacia adelante al ancho de hombros y soltá los seguros.",
    "Bajá despacio el peso hacia el cuerpo, manteniendo los abdominales metidos y las rodillas siguiendo la misma dirección que los pies, hasta 90 grados.",
    "No bloquees las rodillas ni rebotes el peso.",
  ],
  lying_ez_bar_triceps_extension: [
    "Acostate en un banco plano con la cabeza en una punta.",
    "Agarrá una barra Z en pronación.",
    "Subí la barra derecho por encima de los hombros, cuidando de mantener los codos cerca.",
    "Bajá despacio la barra en arco por detrás de la cabeza.",
    "Llevá la barra de vuelta a la posición inicial.",
    "Nota: mantené los brazos firmes durante todo el ejercicio, moviendo solo los codos.",
  ],
  overhead_barbell_press: [
    "Sentate en el banco con las puntas de los pies hacia adelante, la espalda recta y los abdominales metidos.",
    "Agarrá la barra con las palmas hacia afuera y las manos al ancho de hombros",
    "Con la barra delante de la cabeza, empujá hacia arriba estirando los brazos pero sin bloquearlos.",
    "Hacé una pausa arriba y, con un movimiento controlado, bajá la barra a la posición inicial.",
  ],
  overhead_barbell_squat: [
    "Pará con los pies un poco más abiertos que el ancho de hombros, con las puntas apenas hacia afuera.",
    "Agarrá una barra con agarre ancho de arranque, con los brazos y los codos estirados por completo.",
    "Manteniendo la barra por encima de la cabeza, flexioná las rodillas y bajá el cuerpo hasta que los muslos queden paralelos al piso.",
    "Volvé a la posición inicial.",
    "Notas: mantené los pies bien plantados en el piso durante todo el ejercicio. Mantené los abdominales metidos, la espalda firme y el pecho arriba mientras hacés este ejercicio.",
  ],
  plate_raises: [
    "Pará con los pies al ancho de hombros, los abdominales metidos y las rodillas apenas flexionadas.",
    "Agarrá una mancuerna en cada mano, con la palma hacia abajo.",
    "Empezá con la mancuerna a la altura de la cintura.",
    "Subí el brazo izquierdo, manteniendo el codo apenas flexionado y el brazo estirado, hasta alinearlo con el hombro.",
    "Hacé una pausa y, con un movimiento controlado, bajá el brazo a la posición inicial en la cintura.",
    "Repetí con el brazo derecho.",
  ],
  pull_up: [
    "Agarrá la barra de dominadas con las palmas hacia adelante, usando el agarre indicado.",
    "Con los dos brazos estirados sosteniendo la barra al ancho elegido, llevá el torso hacia atrás unos 30 grados generando una curvatura en la zona lumbar y sacando el pecho. Esa es la posición inicial.",
    "Traccioná el torso hacia arriba hasta que la barra toque la parte alta del pecho, llevando los hombros y los brazos hacia abajo y atrás. Exhalá durante esta parte del movimiento.",
    "Después de un segundo en la posición contraída, empezá a inhalar y bajá despacio el torso a la posición inicial, con los brazos estirados por completo y los dorsales bien estirados.",
    "Repetí el movimiento.",
    "Consejo",
    "Concentrate en apretar los músculos de la espalda al llegar a la posición de máxima contracción. El torso tiene que quedar quieto mientras se desplaza y solo se mueven los brazos. Los antebrazos no deberían hacer más trabajo que sostener la barra.",
  ],
  push_up: [
    "Empezá con una flexión básica: acostate boca abajo en el piso o una colchoneta, con los pies juntos y apenas flexionados para apoyarte sobre las puntas.",
    "Poné las manos al ancho de hombros a los costados del pecho.",
    "Meté los abdominales.",
    "Inhalá mientras subís el cuerpo hasta estirar los brazos.",
    "Mantené la cabeza y el cuello alineados con el cuerpo (no mires ni para arriba ni para abajo) y no dejes que la espalda suba ni baje.",
    "Exhalá mientras bajás el cuerpo al piso.",
    "Repetí.",
  ],
  reverse_grip_barbell_row: [
    "Inclinate sobre una barra en un ángulo leve, con las rodillas flexionadas y la espalda recta.",
    "Agarrá la barra en supinación (palmas hacia arriba) y traccioná despacio la barra hacia los abdominales, manteniendo los codos cerca del cuerpo.",
    "Hacé una pausa arriba.",
    "Llevá la barra de vuelta a la posición inicial.",
    "Repetí.",
  ],
  reverse_grip_triceps_pressdown: [
    "Pará delante de una torre de poleas y enganchá una barra a la polea alta.",
    "Agarrá la barra con las palmas hacia arriba.",
    "Manteniendo los codos al costado del cuerpo, traccioná la barra hacia abajo, hacia los muslos.",
    "Hacé una pausa y volvé a la posición inicial.",
    "Nota: puede convenirte poner un pie adelante del otro para tener mejor base.",
  ],
  seated_barbell_overhead_triceps_extension: [
    "Sentate en una silla de respaldo corto y recto con los pies bien apoyados en el piso y la espalda recta.",
    "Agarrá una barra Z o una barra recta con las manos separadas unos 15 cm.",
    "Subí la barra con los brazos estirados por encima de la cabeza y después bajala en arco hacia el piso, por detrás de la cabeza.",
    "Volvé a la posición inicial.",
  ],
  seated_cable_row: [
    "Sentate en una máquina de polea baja con los pies apoyados en los estribos y las rodillas apenas flexionadas.",
    "Con los abdominales metidos y la espalda recta, inclinate apenas hacia adelante para agarrar el maneral en pronación (palmas hacia abajo).",
    "Traé despacio el maneral hacia los abdominales mientras te sentás derecho, manteniendo los codos cerca del pecho.",
    "Hacé una pausa y volvé despacio con el maneral a la posición inicial.",
    "Repetí.",
  ],
  seated_calf_raise: [
    "Sentate en la máquina de gemelos sentado.",
    "Apoyá la parte delantera de los pies en la plataforma.",
    "Poné los muslos debajo de la almohadilla, por encima de las rodillas.",
    "Destrabá la barra y subí despacio las puntas de los pies lo más alto posible.",
    "Hacé una pausa y volvé a la posición inicial.",
    "Nota: practicá movimientos lentos y precisos en este ejercicio.",
  ],
  seated_dumbbell_overhead_triceps_extension: [
    "Sentate en el borde de un banco con los pies apoyados en el piso.",
    "Sostené una mancuerna en cada mano.",
    "Subí los brazos al costado hasta que la mancuerna quede casi paralela al pecho, manteniendo el antebrazo vertical.",
    "Empujá el brazo hacia atrás en arco, hacia la espalda.",
    "Volvé a la posición inicial, repetí y cambiá de brazo.",
  ],
  seated_rear_lateral_raise: [
    "Sentate en el borde de un banco con los pies apoyados en el piso delante tuyo.",
    "Apoyá el pecho sobre los muslos con la espalda recta y agarrá las poleas con las manos cruzadas.",
    "Subí los brazos hasta la altura de los hombros. Hacé una pausa arriba.",
    "Bajá los brazos a la posición inicial con un movimiento controlado.",
    "Repetí.",
  ],
  single_arm_dumbbell_shoulder_press: [
    "Pará con los pies al ancho de hombros, la espalda recta y los abdominales metidos.",
    "Agarrá una mancuerna con la mano y subila con el codo flexionado hasta la altura del hombro para empezar.",
    "Subí la mancuerna derecho hasta estirar el brazo por completo por encima de la cabeza.",
    "Bajá de manera controlada y volvé a la posición inicial.",
    "Repetí.",
  ],
  smith_machine_bench_press: [
    "Poné un banco plano en el medio de la máquina Smith, con la barra alineada con el medio del pecho.",
    "Acostado en el banco, agarrá la barra al ancho de hombros.",
    "Destrabá la barra y bajala despacio hasta el pecho.",
    "Estirá los brazos por completo y subí la barra a la posición inicial.",
    "Repetí.",
  ],
  squats_with_band: [
    "Pará con los pies sobre las bandas elásticas, al ancho de hombros.",
    "Agarrá las manijas de las bandas y subilas hasta los hombros.",
    "Con los abdominales metidos, bajá en sentadilla hasta que los muslos queden paralelos al piso.",
    "Volvé despacio a la posición inicial.",
    "Nota: mantené los pies bien plantados en el piso durante todo el ejercicio.",
  ],
  standing_barbell_calf_raise: [
    "Poné un cajón o dos discos en el piso.",
    "Apoyá una barra sobre la espalda y subí de modo que la parte delantera de los pies quede sobre el cajón.",
    "Subí despacio los talones y después bajalos al piso, buscando el mayor estiramiento posible.",
    "Volvé a la posición inicial.",
  ],
  t_bar_row: [
    "Poné los pies a cada lado de la máquina de remo T.",
    "Con las rodillas apenas flexionadas y los abdominales metidos, agarrá los manerales con agarre cerrado.",
    "Flexioná desde la cintura de modo que el pecho quede paralelo al piso: esa es la posición inicial. Traccioná despacio la barra hacia el pecho, lo más alto que puedas.",
    "Hacé una pausa arriba y bajá la barra a la posición inicial.",
    "Repetí",
  ],
  trx_inverted_row: [
    "Acostate debajo de una barra de modo que quede a la altura media del pecho y con los pies bien apoyados en el piso.",
    "Meté los abdominales y mantené la espalda recta.",
    "Con los brazos, traccioná el cuerpo hacia la barra.",
    "Hacé una pausa y, con movimientos lentos y controlados, bajá a la posición inicial.",
    "Repetí.",
  ],
  walking_lunge: [
    "Empezá apoyando una barra sobre la parte alta de la espalda o agarrando una mancuerna en cada mano.",
    "Pará con los pies separados unos 20 cm, las puntas hacia adelante.",
    "Dá una zancada hacia adelante manteniendo los abdominales metidos y el tronco derecho.",
    "Bajá despacio una rodilla como si te arrodillaras, manteniendo la otra rodilla flexionada a 90 grados; no dejes que la rodilla toque el piso.",
    "Bajá el cuerpo hasta justo por encima del piso y aguantá un momento antes de empujar con el pie de atrás.",
    "Pasá al frente y repetí el ejercicio con la otra pierna.",
  ],
  weight_plate_front_raise: [
    "Pará con los pies al ancho de hombros, los abdominales metidos y las rodillas apenas flexionadas.",
    "Agarrá una mancuerna en cada mano, con la palma hacia abajo.",
    "Empezá con la mancuerna a la altura de la cintura.",
    "Subí el brazo izquierdo, manteniendo el codo apenas flexionado y el brazo estirado, hasta alinearlo con el hombro.",
    "Hacé una pausa y, con un movimiento controlado, bajá el brazo a la posición inicial en la cintura.",
    "Repetí con el brazo derecho.",
  ],
  weighted_barbell_rollout: [
    "Poné una barra en el piso, a la altura de los pies.",
    "Flexionando desde la cintura, agarrá la barra en pronación al ancho de hombros.",
    "Con un movimiento lento y controlado, rodá la barra hacia adelante hasta que la espalda quede recta.",
    "Mantené los brazos estirados durante todo el ejercicio.",
    "Rodá de vuelta subiendo las caderas y la cola mientras volvés a la posición inicial.",
    "Nota: practicá subir las caderas y la cola lo más alto que puedas en este ejercicio.",
  ],
  weighted_side_bend: [
    "Este ejercicio usa una pelota de estabilidad en lugar de un banco. La pelota se adapta mejor al cuerpo y permite un rango de movimiento anatómicamente correcto.",
    "Acostate sobre un costado del torso y, con la cintura y la cadera apoyadas contra la pelota, apoyá los pies en el piso (o contra una pared) para sostenerte.",
    "Con una mano, sostené un peso contra el costado de la cabeza.",
    "Poné la mano libre cruzada sobre el pecho para estabilizarte.",
    "Subí el torso separándolo de la pelota flexionando la cintura.",
    "Con movimientos controlados, bajá de vuelta sobre la pelota.",
  ],
  wide_grip_barbell_bench_press: [
    "Acostate en un banco plano con los pies apoyados en el piso.",
    "Poné las manos más anchas que el ancho de hombros en la barra y sacala del rack: esa es la posición inicial.",
    "Llevá la barra por encima del pecho y bajala hasta que quede justo por encima del cuerpo.",
    "Estirá los brazos hacia arriba y subí la barra derecho.",
    "Hacé una pausa y, con un movimiento lento y controlado, llevá la barra a la posición inicial.",
    "Repetí.",
  ],
  wide_stance_barbell_squat: [
    "Sacá la barra del rack y apoyala sobre los hombros.",
    "Pará con los pies más abiertos que el ancho de hombros (unos 75 cm) con las puntas hacia afuera.",
    "Con los abdominales metidos, bajá despacio flexionando rodillas y caderas, como si te sentaras (sentadilla).",
    "Bajá todo lo que puedas controlar sin que el cuerpo se vaya hacia las puntas de los pies (eso te hace perder el equilibrio).",
    "Hacé una pausa abajo y volvé despacio a la posición inicial.",
    "Nota: una almohadilla en la barra o una toalla en los hombros puede mejorar el agarre y reducir la molestia de la barra contra la espalda. Practicá la sentadilla sin peso para familiarizarte con el movimiento.",
  ],
};
