// Mapeo curado: catalogId → slug de la ilustración de Everkinetic (CC-BY-SA-4.0).
// Curado A MANO ejercicio por ejercicio, NO por similitud de nombre: un dibujo parecido
// enseña mal el movimiento. Los que no están acá simplemente no tienen ilustración
// (Everkinetic no cubre kettlebell, TRX, face pulls, plancha frontal ni nada colgado de barra).
//
// Los assets todavía NO están en el repo: los baja la ingesta de la Pieza 1
// (ver docs/superpowers/specs/2026-07-18-gifs-ejercicios-design.md). Este archivo preserva
// la curación, que es el trabajo caro y difícil de reproducir.
export const EXERCISE_MEDIA_SLUGS: Record<string, string> = {
  alternating_dumbbell_lunge: "dumbbell-lunges",
  arnold_press: "arnold-press",
  barbell_back_squat: "barbell-squat",
  barbell_bench_press: "bench-press",
  barbell_biceps_curl: "biceps-curls-with-barbell",
  barbell_deadlift: "barbell-dead-lifts",
  barbell_front_squat: "front-squat-with-barbell",
  barbell_hack_squat: "hack-squat-with-barbell",
  barbell_lunge: "barbell-lunges",
  barbell_rollout: "ab-rollout-with-barbell",
  barbell_row: "bent-over-row-with-barbell",
  barbell_shoulder_press: "barbell-shoulder-press",
  barbell_shrug: "barbell-shrugs",
  barbell_step_up: "step-ups-with-barbell",
  barbell_upright_row: "upright-barbell-rows",
  behind_the_back_smith_machine_shrug: "smith-machine-shoulder-shrugs",
  bench_dip: "bench-dips",
  bent_over_lateral_raise: "bent-over-lateral-cable-raises",
  bicycle_crunch: "air-bike",
  body_weight_dip: "tricep-dips-using-body-weight",
  cable_biceps_curl: "standing-biceps-curl-with-cable",
  cable_crossover: "cable-crossover",
  cable_front_raise: "front-cable-raises",
  cable_hammer_curl: "hammer-curls-with-rope-and-cable",
  cable_internal_rotation: "internal-cable-rotation",
  cable_lying_triceps_extension: "lying-triceps-extension-with-cable",
  chin_up: "chin-ups",
  close_grip_barbell_bench_press: "close-grip-barbell-bench-press",
  close_grip_ez_bar_biceps_curl: "close-grip-ez-bar-curl-with-barbell",
  close_grip_lat_pulldown: "v-bar-pull-down",
  cross_body_dumbbell_hammer_curl: "cross-body-hammer-curl-with-dumbbell",
  crunch: "crunches",
  decline_dumbbell_bench_press: "decline-dumbbell-bench-press",
  decline_dumbbell_flye: "decline-dumbbell-flys",
  decline_push_up: "push-up-feet-elevated-2",
  diamond_push_up: "close-triceps-pushup",
  donkey_calf_raise: "donkey-calf-raises",
  dumbbell_bench_press: "bench-press-dumbbell",
  dumbbell_biceps_curl: "biceps-curl-with-dumbbell",
  dumbbell_deadlift: "dumbbell-dead-lifts",
  dumbbell_flye: "dumbbell-flys",
  dumbbell_front_raise: "front-dumbbell-raise",
  dumbbell_hammer_curl: "biceps-hammer-curl-with-dumbbell",
  dumbbell_kickback: "triceps-kickback-with-dumbbell",
  dumbbell_lateral_raise: "lateral-dumbbell-raises",
  dumbbell_lunge: "dumbbell-lunges",
  dumbbell_lying_triceps_extension: "lying-triceps-extension-with-dumbbells",
  dumbbell_shoulder_press: "dumbbell-shoulder-press",
  dumbbell_shrug: "shoulder-shrugs",
  dumbbell_squat: "squats-using-dumbbells",
  dumbbell_step_up: "step-ups-with-dumbbells",
  dumbbell_upright_row: "dumbbell-upright-rows",
  ez_bar_overhead_triceps_extension: "standing-overhead-triceps-extension-with-barbell",
  ez_bar_preacher_curl: "preacher-curl-with-barbell",
  ez_bar_pullover: "bent-arm-pullover",
  flutter_kicks: "flutter-kicks",
  front_raise: "front-raises",
  incline_barbell_bench_press: "incline-bench-press",
  incline_dumbbell_bench_press: "dumbbell-incline-bench-press",
  incline_dumbbell_biceps_curl: "incline-inner-biceps-curl-with-dumbbell",
  incline_dumbbell_flye: "incline-dumbbell-flys",
  incline_smith_machine_bench_press: "smith-machine-incline-bench-press",
  leg_lift: "body-leg-lifts",
  leg_press: "leg-press",
  lying_ez_bar_triceps_extension: "lying-triceps-press-with-barbell",
  overhead_barbell_press: "seated-military-press",
  overhead_barbell_squat: "overhead-squat-with-barbell",
  plate_raises: "front-raises",
  pull_up: "pull-ups",
  push_up: "push-ups",
  reverse_grip_barbell_row: "reverse-grips-bent-over-barbell-rows",
  reverse_grip_triceps_pressdown: "reverse-grip-triceps-pushdown",
  seated_barbell_overhead_triceps_extension: "seated-overhead-triceps-extension-with-barbell",
  seated_cable_row: "seated-cable-rows",
  seated_calf_raise: "seated-calf-raise-using-machine",
  seated_dumbbell_overhead_triceps_extension: "seated-two-arm-triceps-extension-with-dumbbell",
  seated_rear_lateral_raise: "seated-rear-lateral-cable-raise",
  single_arm_dumbbell_overhead_triceps_extension: "standing-one-arm-triceps-extension-with-dumbbell",
  single_arm_dumbbell_shoulder_press: "one-arm-dumbbell-shoulder-press",
  smith_machine_bench_press: "smith-machine-bench-press",
  squats_with_band: "squats-with-exercise-bands",
  standing_barbell_calf_raise: "standing-barbell-calf-raise",
  standing_calf_raise: "standing-calf-raise-with-dumbbell",
  standing_dumbbell_calf_raise: "standing-calf-raise-with-dumbbell",
  t_bar_row: "t-bar-rows",
  trx_inverted_row: "body-row",
  walking_lunge: "walking-lunges",
  weight_plate_front_raise: "front-raises",
  weighted_barbell_rollout: "ab-rollout-with-barbell",
  weighted_side_bend: "weighted-ball-side-bend",
  wide_grip_barbell_bench_press: "wide-grip-bench-press",
  wide_grip_lat_pulldown: "wide-grip-lat-pull-down",
  wide_stance_barbell_squat: "wide-stance-squat-with-barbell",
};
